name: skipapp-weather
on:
  push:
    branches: '*'
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron: '30 3,13 * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  call-workflow:
    uses: skiptools/actions/.github/workflows/skip-app.yml@v1
